
import type { NavData, Testimonial, FaqItem, PillItem, Course } from '../types';

export const navData: NavData = {
    premium: { href: "#", title: "Cours Premium", sectionId: "cours" },
    courses: {
        title: "Courses",
        columns: 3,
        links: [
            { href: "#", title: "Courses (All)", icon: "grid", categoryKey: "all" },
            { href: "#", title: "Ecommerce", icon: "shopping-cart", categoryKey: "ecommerce"},
            { href: "#", title: "SMMA", icon: "share-2", categoryKey: "smma"},
            { href: "#", title: "Marketing", icon: "target", categoryKey: "marketing"},
            { href: "#", title: "Trading", icon: "bar-chart-2", categoryKey: "trading"},
            { href: "#", title: "Immobilier", icon: "home", categoryKey: "immobilier"},
            { href: "#", title: "Cryptomonnaie", icon: "https://cdn.simpleicons.org/bitcoin/white", iconType: "img", categoryKey: "crypto"},
            { href: "#", title: "Business", icon: "briefcase", categoryKey: "business"},
            { href: "#", title: "OFM", icon: "https://cdn.simpleicons.org/onlyfans/white", iconType: "img", categoryKey: "ofm"},
            { href: "#", title: "Code/Nocode", icon: "code", categoryKey: "nocode"},
            { href: "#", title: "Editing / Montage", icon: "scissors", categoryKey: "editing"},
            { href: "#", title: "After Effects (Ae)", icon: "layers", categoryKey: "after-effects" },
            { href: "#", title: "UX/UI", icon: "pen-tool", categoryKey: "ux-ui" },
            { href: "#", title: "Houdini", icon: "box", categoryKey: "houdini" },
            { href: "#", title: "Photoshop (Ps)", icon: "image", categoryKey: "photoshop" },
            { href: "#", title: "Illustrator (Ai)", icon: "edit-3", categoryKey: "illustrator" },
            { href: "#", title: "Premiere Pro (Pr)", icon: "film", categoryKey: "premiere-pro" },
            { href: "#", title: "Blender", icon: "package", categoryKey: "blender" },
            { href: "#", title: "Cinema 4D (C4D)", icon: "codepen", categoryKey: "cinema-4d" },
            { href: "#", title: "Unreal Engine (UE)", icon: "cpu", categoryKey: "unreal-engine" },
            { href: "#", title: "Maya", icon: "move", categoryKey: "maya" },
            { href: "#", title: "Nuke", icon: "disc", categoryKey: "nuke" },
            { href: "#", title: "Davinci Resolve", icon: "sliders", categoryKey: "davinci-resolve" },
            { href: "#", title: "Filmmaking", icon: "video", categoryKey: "filmmaking" },
            { href: "#", title: "AI", icon: "cpu", categoryKey: "ai" }
        ]
    },
    platforms: {
        title: "Plateformes & Créateurs",
        columns: 1,
        links: [
            { href: "#", title: "Skillshare", icon: "book-open" },
            { href: "#", title: "Udemy", icon: "award" },
            { href: "#", title: "Domestika", icon: "globe" },
            { href: "#", title: "Coloso", icon: "briefcase" },
            { href: "#", title: "Patreon Creators", icon: "users", categoryKey: "patreon" },
        ]
    },
    design: {
        title: "Design & UX",
        columns: 2,
        links: [
            { href: "#", title: "Motion Graphics", icon: "wind" },
            { href: "#", title: "UX/UI", icon: "pen-tool", categoryKey: "ux-ui" },
            { href: "#", title: "Books", icon: "book" },
            { href: "#", title: "Graphic Design", icon: "edit-3", categoryKey: "graphic-design" },
            { href: "#", title: "3D Modeling", icon: "box" },
            { href: "#", title: "Character Design", icon: "user" },
            { href: "#", title: "Concept Art", icon: "image" },
        ]
    },
    video: {
        title: "Ressources Vidéo",
        columns: 2,
        links: [
            { href: "#", title: "Visual Effects (VFX)", icon: "zap" },
            { href: "#", title: "Video Editing", icon: "scissors", categoryKey: "editing" },
            { href: "#", title: "Animation", icon: "play-circle" },
            { href: "#", title: "Game Development", icon: "airplay" },
            { href: "#", title: "Photography", icon: "camera" },
            { href: "#", title: "Sound Effects", icon: "volume-2" },
        ]
    },
    theme: {
        title: "Theme",
        columns: 1,
        links: [
            { href: "#", title: "Iris", icon: "droplet" },
            { href: "#", title: "Pristine", icon: "droplet" },
            { href: "#", title: "Boss", icon: "droplet" },
        ]
    }
};

export const coursesData: Course[] = [
    { 
        id: 1, 
        title: 'Digital Domination Mastery Ver 1.02 (Creator to Profit)', 
        date: 'October 23, 2025', 
        categories: ['ecommerce', 'business'], 
        img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-31-680x553.png', 
        description: "Learn the secrets to turning your creative skills into a profitable online business.",
        status: 'published',
    },
    { 
        id: 2, 
        title: 'The Clips Academy', 
        date: 'October 22, 2025', 
        categories: ['editing', 'smma'], 
        img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-15-3-680x553.png', 
        description: "Master the art of creating viral short-form video content for social media.",
        content: `
            <h1 class="text-3xl font-bold mb-4">Format of Videos – PREMIUM (no mp4) </h1>
            <h6 class="text-lg font-semibold mb-4 text-white/80">Master Premium Editing Skills, Get Elite 1-On-1 Mentorship, And Unlock Guaranteed Job Opportunities With The Signature Editor Challenge.</h6>
            <p class="mb-4 text-white/70">Master the art of branded, high-impact content. In just 60 days, you’ll go beyond the basics and build skills that make you indispensable.</p>
            <p class="mb-6 text-white/70">You will get:<br>— 8 weeks<br>— All assets<br>— Branded Video Editing<br>— Signature Style Creation<br>— Future Updates</p>
        `,
        status: 'published',
    },
    { 
        id: 3, 
        title: 'Motion Flyer', 
        date: 'October 22, 2025', 
        categories: ['after-effects', 'editing'], 
        img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-14-4-680x553.png', 
        description: "Bring your event flyers to life with stunning motion graphics in After Effects.",
        externalLink: 'https://google.com/search?q=Motion+Flyer+Course',
        status: 'published',
    },
    { id: 4, title: 'Visual Hub', date: 'October 22, 2025', categories: ['editing'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-12-7-680x553.png', description: "A comprehensive library of visual assets and tutorials for modern creators.", status: 'published' },
    { id: 25, title: 'Sparvol - All Pack + Course', date: 'October 15, 2025', categories: ['editing'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-11-3-680x553.png', description: "Get the complete Sparvol collection of video editing assets and an exclusive course.", status: 'published' },
    { id: 26, title: 'Sparvol - Short Form Timelines & Hooks', date: 'October 15, 2025', categories: ['editing', 'marketing'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-10-4-680x553.png', description: "Learn how to structure your short videos for maximum retention and engagement.", status: 'published' },
    { id: 5, title: 'Render Room', date: 'October 31, 2025', categories: ['premium', 'blender', 'cinema-4d'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-34-680x553.png', description: "An exclusive community and resource hub for 3D rendering artists.", status: 'published' },
    { id: 6, title: 'Design Academy - Logo Design Mega Course', date: 'October 15, 2025', categories: ['premium', 'ux-ui', 'illustrator'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-3-4-680x553.png', description: "A to Z of logo design principles and techniques for creating iconic brands.", status: 'published' },
    { id: 7, title: 'Keanu Visuals - Samsung Module', date: 'October 13, 2025', categories: ['premium', 'after-effects', 'editing'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-23-680x553.png', description: "Learn to create high-end product commercials with a focus on slick, corporate aesthetics.", status: 'published' },
    { id: 27, title: 'Editing Lair, Full October Updates And Call Recordings', date: 'October 11, 2025', categories: ['premium', 'editing'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-5-2-680x553.png', description: "Access the complete archive of a professional video editor's monthly updates and coaching calls.", status: 'published' },
    { id: 28, title: 'Process Masterclass - Advance your design career', date: 'October 11, 2025', categories: ['premium', 'ux-ui', 'business'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-4-2-680x553.png', description: "Go beyond the tools and learn the professional process of a successful design career.", status: 'published' },
    { id: 8, title: 'Arpit Brandings 23 Mockups Bundle', date: 'October 31, 2025', categories: ['ux-ui', 'photoshop'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-3-11.png', description: "A massive bundle of 23 high-quality mockups for branding projects.", status: 'published' },
    { id: 9, title: 'HardRender.app 22 Mockups Bundle', date: 'October 31, 2025', categories: ['ux-ui', 'photoshop'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-2-10.png', description: "Showcase your designs with this collection of 22 photorealistic mockups.", status: 'published' },
    { id: 10, title: 'Render Team 141 Mockups Bundle', date: 'October 31, 2025', categories: ['ux-ui', 'photoshop'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-1-10.png', description: "The ultimate mockup collection with 141 unique and versatile templates.", status: 'published' },
    { id: 11, title: 'Vitora Mockup - Automotive Car Garage Branding Mockup', date: 'October 30, 2025', categories: ['ux-ui', 'photoshop'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-20-3.png', description: "Present your automotive branding concepts with this detailed garage mockup.", status: 'published' },
    { id: 12, title: 'Vitora Mockup - Milk Company & Store Branding Mockup', date: 'October 30, 2025', categories: ['ux-ui', 'photoshop'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-19-3.png', description: "A complete branding mockup set for a milk company, from packaging to storefront.", status: 'published' },
    { id: 13, title: 'CGCircuit - Building Fluid Solvers for VFX and Houdini - Part 2', date: 'October 30, 2025', categories: ['houdini'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-3-10.png', description: "Dive deeper into the mathematics and code behind professional fluid solvers in Houdini.", status: 'published' },
    { id: 14, title: 'CGCircuit - Building Fluid Solvers for VFX and Houdini - Part 1', date: 'October 30, 2025', categories: ['houdini'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-2-9.png', description: "Learn to build your own fluid solvers from scratch for ultimate control over your VFX.", status: 'published' },
    { id: 15, title: 'FXPHD - RND211 - RenderMan for Houdini Solaris', date: 'October 30, 2025', categories: ['houdini'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-1-9.png', description: "Master Pixar's RenderMan within the powerful Solaris context in Houdini for feature-film quality rendering.", status: 'published' },
    { id: 16, title: 'FXPHD - HOU232 - Creating Fire and Smoke Simulations in Houdini and Axiom', date: 'October 30, 2025', categories: ['houdini'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-33.png', description: "Create realistic and art-directable fire and smoke using Houdini's native tools and the Axiom solver.", status: 'published' },
    { id: 17, title: 'Boom Library - Riparian Zones', date: 'September 25, 2025', categories: ['editing'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-4-5.png', description: "A high-quality sound library capturing the ambiences of riversides and wetlands.", status: 'published' },
    { id: 18, title: 'Boom Library - Medieval Life', date: 'September 25, 2025', categories: ['editing'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-3-4.png', description: "Transport your audience to the middle ages with this authentic sound effects collection.", status: 'published' },
    { id: 19, title: 'Boom Library - Nature Essentials', date: 'September 25, 2025', categories: ['editing'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-2-7.png', description: "An essential toolkit of high-quality, versatile nature sounds for any project.", status: 'published' },
    { id: 20, title: 'Boom Library - Canyons Stereo + Surround', date: 'September 25, 2025', categories: ['editing'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-1-7.png', description: "Immersive soundscapes from vast canyons, available in both stereo and surround formats.", status: 'published' },
    { id: 21, title: 'Patreon - Redblueen', date: 'October 15, 2025', categories: ['patreon'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-3-5.png', description: "Exclusive content and tutorials from the popular digital artist Redblueen.", status: 'published' },
    { id: 22, title: 'Patreon - Hoang Nguyen', date: 'October 15, 2025', categories: ['patreon'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-2-4.png', description: "Access behind-the-scenes content and project files from 3D artist Hoang Nguyen.", status: 'published' },
    { id: 23, title: 'Pizola', date: 'September 2, 2025', categories: ['patreon', 'photoshop'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-2-2.png', description: "Join Pizola's Patreon for exclusive Photoshop tutorials and resources.", status: 'published' },
    { id: 24, title: 'Cleverpoly', date: 'September 2, 2025', categories: ['patreon', 'blender'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-1-2.png', description: "Learn low-poly 3D modeling and game art with Cleverpoly's exclusive Patreon content.", status: 'published' },
    { id: 100, title: 'Wingfox – Create Two Anime-Stylized Scenes in Blender', date: 'October 20, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-28-680x553.png', description: 'Content: HD videos, Resources Duration: 5 Hours 32 Minutes / 25 lessons Software: Blender...', status: 'published' },
    { id: 101, title: 'Hulk Fat Worm – Blender “Car Hard Surface Practical Advanced Course”', date: 'October 18, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-4-4-680x553.png', description: 'A practical, advanced course on hard surface modeling for vehicles in Blender.', status: 'published' },
    { id: 102, title: 'Momentor – Blender Styleframe', date: 'October 17, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-27-680x553.png', description: 'Learn the professional workflow for creating stunning styleframes for motion design projects in Blender.', status: 'published' },
    { id: 103, title: 'Blender & AE Ultimate Training Guide', date: 'October 11, 2025', categories: ['blender', 'after-effects'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-2-2-680x553.png', description: 'Integrate Blender and After Effects to create amazing 3D and 2D motion graphics.', status: 'published' },
    { id: 104, title: 'Blender Super Training Guide – Become an expert without even realizing it!', date: 'October 11, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-1-3-680x553.png', description: 'A comprehensive guide that takes you from beginner to expert in Blender through practical projects.', status: 'published' },
    { id: 105, title: 'Viscous Realm – Marshy Mansions PREMIUM', date: 'October 7, 2025', categories: ['blender', 'premium'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-5-1-680x553.png', description: 'What will You Learn? We will be making everything from start to finish so therefore this course will go...', status: 'published' },
    { id: 106, title: 'Mecha In Blender – Rms-099 Timelapse', date: 'October 7, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-2-1-680x553.png', description: 'Timelapses of mecha projects were posted to my YouTube channel, but they are sped up x20 making...', status: 'published' },
    { id: 107, title: 'Mecha In Blender – Ms-06 Timelapse', date: 'October 7, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-1-1-680x553.png', description: 'Timelapses of mecha projects were posted to my YouTube channel, but they are sped up x20 making...', status: 'published' },
    { id: 108, title: 'Mecha In Blender – Rx-78 Timelapse', date: 'October 7, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-20-680x553.png', description: 'Timelapses of mecha projects were posted to my YouTube channel, but they are sped up x20 making...', status: 'published' },
    { id: 109, title: 'Blender Geometry Nodes: Alien Worlds – Tentacles, Terrain & Lighting Masterclass', date: 'October 2, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-16-680x553.png', description: 'Project Title: Blender Geometry Nodes Alien Worlds – Tentacles, Terrain & Lighting Masterclass Project...', status: 'published' },
    { id: 110, title: 'Fire simulation in Blender', date: 'October 2, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-11-680x553.png', description: 'À propos de ce cours Making fire in blender is difficult. That is why i made this class to help you out. In...', status: 'published' },
    { id: 111, title: 'Refraction Shader in Blender – Make a Stylized Glass Material', date: 'October 2, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-6-680x553.png', description: 'About This Class Are you ready to explore the playful side of 3D art and discover the magic of refractive...', status: 'published' },
    { id: 112, title: 'Your First Beauty Product Animation in Blender', date: 'October 2, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/10/Courses-5-680x553.png', description: 'About This Class Want to learn how to create a complete 3D beauty product animation from...', status: 'published' },
    { id: 113, title: 'Fast Track Tutorials – Creating Stylized 3D Environments for Games', date: 'September 28, 2025', categories: ['blender', 'photoshop', 'unreal-engine'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-21-680x553.png', description: 'About This Class Stylized Environment Art in Unreal Engine 5 – In-Depth Tutorial Course Learn how a...', status: 'published' },
    { id: 114, title: 'Fast Track Tutorials – Creating Low-Poly Stylized 3D Weapons', date: 'September 28, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-19-680x553.png', description: 'About This Class Creating Low-Poly Stylized 3D Weapons – In-Depth Tutorial Course Learn how a...', status: 'published' },
    { id: 115, title: 'Blender Uncovered PREMIUM', date: 'September 27, 2025', categories: ['blender', 'premium'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-9-4-680x553.png', description: 'This Blender course is an introduction to the world of 3D design. Covering everything from workspace...', status: 'published' },
    { id: 116, title: 'Beginner Motion Graphics with Fluid Simulation in Blender PREMIUM', date: 'September 27, 2025', categories: ['blender', 'premium'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-8-2-680x554.png', description: 'What you will learn Prerequisites Blender UI basics and navigating in a 3D space. General art...', status: 'published' },
    { id: 117, title: 'Take your Cinematic 3D Animations to the next Level in Blender! PREMIUM', date: 'September 27, 2025', categories: ['blender', 'premium'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-15-1.png', description: 'In this course, I will teach you what took me years and hundreds of tutorials to learn! We will dive into...', status: 'published' },
    { id: 118, title: 'Blender Fundamentals PREMIUM', date: 'September 27, 2025', categories: ['blender', 'premium'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-13-1.png', description: 'From character modeling to rigging and animation, our Blender course offers a wealth of knowledge for...', status: 'published' },
    { id: 119, title: 'Blender 3.0 Master Class for Product Photographers & Designers (From Absolute Beginner to Pro)', date: 'September 27, 2025', categories: ['blender', 'photoshop'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-11-2.png', description: 'Do you want to create advertising quality images and uplift your photography portfolio? Do you want...', status: 'published' },
    { id: 120, title: 'Brand Design Using Blender', date: 'September 27, 2025', categories: ['blender', 'ux-ui'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-9-3.png', description: 'Beyond simple artwork production, 3D graphics include logos, brand key visuals, card news,...', status: 'published' },
    { id: 121, title: 'Interactiv Studio – Master Product Visualisation', date: 'September 27, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-8-1.png', description: 'I Want To GIFT You Everything I’ve Learned From Knowing Nothing About Product Rendering in...', status: 'published' },
    { id: 122, title: 'Blender VFX Course Learn 3D Visual Effects', date: 'September 19, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/09/Courses-1-5.png', description: 'Master the Workflow CORE is designed to teach you the theory and fundamentals of the 3D VFX workflow...', status: 'published' },
    { id: 123, title: 'The ULTIMATE Subd Modeling Program for Blender', date: 'August 31, 2025', categories: ['blender'], img: 'https://madbax.org/wp-content/uploads/2025/08/Courses-1-1.png', description: 'What’s Included? A complete guide to subdivision surface modeling in Blender.', status: 'published' },
];

export const allCoursesForSearch: Course[] = [...new Map(coursesData.map(item => [item['id'], item])).values()];

export const testimonials: Testimonial[] = [
    { author: "ZUX", text: "It is one of the Best Channel so far. Get access to all the materials and courses that is never possible for me without these groups. Thank You admin for this help. I will forever grateful to you and your group. So 5 stars from me. You can literally ask any materials from this group and admins will provide that. Again Thank you very much Admin brothers.", stars: 5 },
    { author: "Deleted Account", text: "I'll be quick, the content is very complete and if you have a request it is resolved in a short time, it definitely exceeded my expectations", stars: 5 },
    { author: "Fazal", text: "The best service I've found on Telegram! They fulfill any request in no time, and the price is what really caught my attention.", stars: 5 },
    { author: "VKEY", text: "First of all, the admin of the group, Keyzo, treats everyone like a brother and sister and helps everyone 24/7. I don't know when he sleeps. I've been here since March and it's been a wonderful experience. I must say, it has been an incredible experience. Content. offers a wide range of projects, allowing me to explore my creativity and collaborate with talented individuals from around the world...", stars: 5 },
    { author: "Deleted Account", text: "This is the kind of group I would never want be dead or gone. This group is like a one of the best investments of my life until now. The admin is really great and understanding. He would even discount if you currently have some financial issues... This group is like a boon for students like me who can't afford to pay a lot at once.", stars: 5 },
    { author: "Jiggly.jpg", text: "The best resources, the best community. Key zo is a legend", stars: 5 },
    { author: "Spiderman", text: "Genuine group with a helpful admin Keyzo. I used my scholarship amount to join the group it's genuine. Also look forward to collaboration, learning with other members and new upcoming courses", stars: 5 },
    { author: "LEGION", text: "Content. has been providing premium courses for a very long time... what differentiate Content. from other channels is the unique courses. Courses and Assets from Content. can only be seen Content. not anywhere else. Key-Zo please dont stop doing this service.", stars: 5 },
    { author: "Mukul", text: "The best resources, the best community. These resources help me alot to grow as a video editor. Keep up the good work man! And also Bro Key zo is an amazing person", stars: 5 },
    { author: "Wane Shadow", text: "Best Group for designers and editors and Everyone who wants to learn new skills. No. 1 Group in the entire telegram, who provides so many Values at a very low price. 10/10", stars: 5 },
    { author: "Prathip G", text: "Really 120% Worth for If you pay Premium. Lot of Assets, Premium Rare Courses. Ever i Haven't purchase any premium group because trust issues except you brother. Really Great Group & It's Really Worth Guys. 10/10", stars: 5 },
    { author: "me", text: "The reason why this group is the best group and different from other groups is the admin support. Admin is like homie, you can reach to him whenever you want, ask him about any problem you're having related to group. He really pays close attention to every requests made by us.", stars: 5 },
    { author: "No Matter", text: "One of the best premium access ever! A very up2date courses you'll never find anywhere else. Thanks to admin-bro!", stars: 5 },
    { author: "Galer", text: "I think this is the best channel that provides fresh courses", stars: 5 },
    { author: "Daebit Tanner", text: "Keyzo is real nice guy... help me out on courses and also flexible on payment system .. its my go to for coures now this channel", stars: 5 },
    { author: "The Zeil", text: "Keyzo really helped me a lot, when it comes to courses and all but the best part is the way he treats everyone in the community with respect and seriousness That is the reason i have trust in the group.", stars: 5 },
    { author: "Jircksy", text: "A huge thank you to Keyzo who helped me purchase a much needed item! Completely satisfied with the group buy", stars: 5 },
    { author: "Max", text: "I personally don't have anything to say, everything is value for money. You get what you are promised to. But I do have a suggestion and I think keyzoo should have some other few people to help him... 5/5", stars: 5 },
    { author: "Omeed Saye", text: "Just Join, Don't even 2nd think it, No He's not a scammer and He cares for the gp, I literally sent him a patreon the other day... and he got it the same day, Absolute legend. If you're a poor nigga, This private gp would help you a ton, It's literally $10 for around $3000 of value, What you waiting for, Just get in.", stars: 5 },
    { author: "Atomicspirit_", text: "I rarely want to invest in a course, a group is a far cry for me to invest but not this one. I was initially sceptical, but the value this offered me far outweighed my investment. I'm thankful to be part of this group... #Goforit", stars: 5 },
    { author: "Nam Nguyen", text: "Never hesitate to join in because All the value you give to me is so precious that I cannot get anywhere else, this group maybe not alot of people but it hella pack full of amazing people, love to be a part of it", stars: 5 },
    { author: "Coco", text: "I decided to take a chance, and it exceeded all my expectations - absolutely worth it! 5 / 5", stars: 5 },
    { author: "iRepair", text: "Quality of video is very good", stars: 5 },
    { author: "Mr Perfect", text: "you can trust blindly to this channel no scam here 5/5", stars: 5 },
    { author: "Rebzen", text: "5/5 - Totally worth every single penny - Insane value that no one provides... Keyzo(the admin) is a very genuine, kind & helpful fella. He totally assures you that you are provided 200% of the value... I'm super satisfied with it from the last 3 months...", stars: 5 },
    { author: "Rafay", text: "I recently purchased a course from Keyzo, and I am beyond impressed! He is a very trustworthy person, always available to assist, and communicates in such a polite and professional manner. Thank you, Keyzo, for an outstanding experience!", stars: 5 },
    { author: "Zac", text: "I got the lifetime membership and it's nothing but value on value with more being added by the day. Content. team is on top of it. Bringing out the freshest courses, tools and assets on the market. All authentic and regular updates. One of the best purchases of 2024 by far. Thank You", stars: 5 },
    { author: "Prince Patel", text: "I also got the lifetime sub and it's preety good deal and also the admin is co operative this group providing value at a best", stars: 5 },
    { author: "Charan K7", text: "I've been a satisfied subscriber for three months, and I can assure you it's worth it. I opted for the lifetime membership, and the value keeps increasing with every update. This Community is consistently ahead... It's hands-down one of the best purchases of 2024. Thank you", stars: 5 },
    { author: "Joel | Victus Global", text: "This is the best investment that you can ever make if you are doubtful of choosing the service , the admin is devoted and would never disappoint you. Its 100% worth it", stars: 5 },
    { author: "User", text: "It's the most value for money purchase I have made in a long time. There are so many premium courses and the admins keep adding new ones... We have a good and very helpful people in the community. ...Absolutely Awesome", stars: 5 },
    { author: "borhane drici", text: "The best of the best number one the admin was perfect . It's too helpful . There's a lot of courses that made learn everything u want . Thank u so much wish u all the best in the future", stars: 5 },
    { author: "User2", text: "I've been a part of this incredible community for over a year now, and it's easily one of the smartest investments I've made... The best part? The people. Keyzo and Lucifer... are genuinely helpful and deeply committed... This isn't just another resource dump it's a tight-knit, multi-disciplinary community... Highly recommended to anyone serious about levelling up.", stars: 5 },
    { author: "The King", text: "You Guys are the best", stars: 5 },
    { author: "Igor", text: "What can I say? First of all, I would like to say thanks to the people who work on it because they provide access to amazing content that has helped me and the community a lot. I'm proud to be in this group.", stars: 5 },
    { author: "R", text: "The genuine one The G.O.A.T", stars: 5 },
    { author: "MINATO SHARMA", text: "This is the Best Group that you will ever find. You will find it worth it and the admins are very much helpful and humble.", stars: 5 },
    { author: "Fruxt0se", text: "the GOAT", stars: 5 },
    { author: "MReza.H", text: "Best community in design...", stars: 5 },
    { author: "Maks Kovsky", text: "A huge amount of money saved thanks to this group. Content is top!", stars: 5 },
    { author: "Daebit Tanner", text: "The best in the game", stars: 5 },
    { author: "Zeta", text: "I don't like bothering Keyzo, but whenever I've needed something, he's always replied. This is a great community full of resources and excellent material. I know Keyzo has been having some health issues. I hope he gets better and recovers soon. Many blessings.", stars: 5 },
    { author: "EAS///", text: "One of the best community i ever joined . I am a part of this community for over a year now and every time i reached out admins they helped me out . Everyone is so helpful and They Share so much valuable courses and assets. Highly recommended . 10/10", stars: 5 },
    { author: "Piro1", text: "The best group in recent times... Admin is simply the best... I was looking for a subscription to CC... here in 10 minutes everything was done... respect", stars: 5 },
    { author: "Mohamed Alzabti", text: "there is no channel on Telegram that provides this useful and educational content, the best channel ever", stars: 5 },
    { author: "Kygo Alae", text: "Great vibes, helpful people, and quality content. Whenever I had a question, the admins replied quickly and shared really valuable materials. Definitely worth joining!", stars: 5 },
    { author: "Muhammad Rayyan", text: "Honest Feedback; Content. has a game changer for me... Everyday.. there's a new course... Admins are extremely supportive... I think if anyone who would want to improve his skills he must need to be a part of this community... it's extremely affordable. Imagine learning Top1% skills then charging premium... Exactly... CONTENT. IS YOUR WAY!", stars: 5 },
    { author: "Pluton", text: "Content. has helped me grow up and find the right resources. Especially the admin he is such a nice person always trying his best to help others. Being a growing video editor the courses provided here are of immense value and for the price we pay it's totally worth every penny", stars: 5 }
];

export const faqData: FaqItem[] = [
  { q: "1. What is Content.?", a: "Content. is an online platform offering creative, design-oriented courses and resources. Its focus spans UI/UX, visual effects, mockups, motion design, 3D animation, and more." },
  { q: "2. How does course access work?", a: "All courses are unlocked through a .gem file. You can access Free Courses, Exclusive Courses, and Group Buy Courses depending on your plan. Group Buy courses become available 30 days later unless you purchase them directly for instant access." },
  { q: "3. Do I have to buy Group Buy courses separately?", a: "Not always. You can either buy immediately if you want early access, or wait 30 days and the course will be added to your account automatically. (This policy may change, so always check for updates.)" },
  { q: "4. What happens if the rules change?", a: "Content. updates its access model from time to time. Always check the Membership or Course Access section for the latest updates." },
  { q: "5. Can I request new courses?", a: "Content. continuously adds courses.. If you'd like to suggest specific topics or creators, you can reach out to our team." },
  { q: "6. What subscription plans are available?", a: "Content. offers multiple plans: Basic (30 Days) → 3 courses/month; Standard (60 Days) → 5 courses/month; Premium (365 Days) → 10 courses/month; Lifetime Plan → 15 courses/month." },
  { q: "7. Do unused course slots carry over to the next month?", a: "No. Course limits reset monthly. For example, if your plan allows 5 courses per month but you only use 3, the remaining 2 do not roll over." },
];

export const softwarePillsData: PillItem[] = [
    { href: "#", category: "ecommerce", icon: "https://cdn.simpleicons.org/shopify/white", iconType: "img", name: "Ecommerce", count: "42 Articles", linkType: 'category' },
    { href: "#", category: "smma", icon: "share-2", iconType: "feather", name: "SMMA", count: "28 Articles", linkType: 'category' },
    { href: "#", category: "marketing", icon: "target", iconType: "feather", name: "Marketing", count: "55 Articles", linkType: 'category' },
    { href: "#", category: "trading", icon: "bar-chart-2", iconType: "feather", name: "Trading", count: "18 Articles", linkType: 'category' },
    { href: "#", category: "immobilier", icon: "home", iconType: "feather", name: "Immobilier", count: "12 Articles", linkType: 'category' },
    { href: "#", category: "crypto", icon: "https://cdn.simpleicons.org/bitcoin/white", iconType: "img", name: "Cryptomonnaie", count: "25 Articles", linkType: 'category' },
    { href: "#", category: "business", icon: "briefcase", iconType: "feather", name: "Business", count: "30 Articles", linkType: 'category' },
    { href: "#", category: "ofm", icon: "https://cdn.simpleicons.org/onlyfans/white", iconType: "img", name: "OFM", count: "9 Articles", linkType: 'category' },
    { href: "#", category: "nocode", icon: "code", iconType: "feather", name: "Code/Nocode", count: "15 Articles", linkType: 'category' },
    { href: "#", category: "editing", icon: "scissors", iconType: "feather", name: "Editing / Montage", count: "17 Articles", linkType: 'category' },
    { type: 'separator', text: 'Design Fr - US' },
    { href: "#", category: "patreon", icon: "https://cdn.simpleicons.org/patreon/white", iconType: "img", name: "Patreon", count: "37 Articles", linkType: 'category' },
    { href: "#", category: "blender", icon: "https://cdn.simpleicons.org/blender/white", iconType: "img", name: "Blender", count: "31 Articles", linkType: 'category' },
    { href: "#", category: "cinema-4d", icon: "https://cdn.simpleicons.org/cinema4d/white", iconType: "img", name: "Cinema 4d", count: "19 Articles", linkType: 'category' },
    { href: "#", category: "unreal-engine", icon: "https://cdn.simpleicons.org/unrealengine/white", iconType: "img", name: "Unreal Engine", count: "6 Articles", linkType: 'category' },
    { href: "#", category: "houdini", icon: "https://cdn.simpleicons.org/houdini/white", iconType: "img", name: "Houdini", count: "10 Articles", linkType: 'category' },
    { href: "#", category: "ux-ui", icon: "https://cdn.simpleicons.org/figma/white", iconType: "img", name: "UX/UI", count: "31 Articles", linkType: 'category' },
    { href: "#", category: "after-effects", icon: "Ae", iconType: "text", name: "After Effects", count: "43 Articles", linkType: 'category' },
    { href: "#", category: "davinci-resolve", icon: "https://cdn.simpleicons.org/davinciresolve/white", iconType: "img", name: "Davinci Resolve", count: "6 Articles", linkType: 'category' },
    { href: "#", category: "photoshop", icon: "Ps", iconType: "text", name: "Photoshop", count: "12 Articles", linkType: 'category' },
    { href: "#", category: "premiere-pro", icon: "Pr", iconType: "text", name: "Premiere Pro", count: "2 Articles", linkType: 'category' },
    { href: "#", category: "illustrator", icon: "Ai", iconType: "text", name: "Illustrator", count: "8 Articles", linkType: 'category' },
];
